---
wrappers:
  public:
    version: v3.13.7
  personal:
    base_url: https://github.com/hermidalc/snakemake-wrappers/raw/main
  local:
    base_url: file:wrappers

random_seed: 777

download:
  retries: 5
  retry_wait: 5

resources:
  ref:
    name: T2T-CHM13v2
    fasta_url: "https://ftp.ncbi.nlm.nih.gov/\
                genomes/all/GCF/009/914/755/GCF_009914755.1_T2T-CHM13v2.0/\
                GCF_009914755.1_T2T-CHM13v2.0_genomic.fna.gz"
  db:
    name: MicrobialDB
    base_dir: resources/kraken2/db
    svc:
      local_dir: /dev/shm
      remote_dir: /lscratch
    libs:
      kraken2:
        names: [archaea, bacteria, viral, human, UniVec_Core]
        nucl_only: [UniVec, UniVec_Core]
        ftp_only: [bacteria]
      krakenuniq:
        names: [refseq/archaea, refseq/bacteria, refseq/viral]
      custom:
          eupathdb:
            nucl:
              base_url: ftp://ftp.ccb.jhu.edu/pub/data/EuPathDB54
              fa_tgz_fname: eupathDB54_CLEAN.tar.gz
              idmap_fname: seqid2taxid_eupathDB54.map
            prot:
              base_url: ''
              fa_tgz_fname: eupathdb_prot.tar.gz
    bracken:
      readlens: [25, 35, 50, 75, 100, 125, 150]

gdc:
  study_name: tcga_wgs
  project_name: primary_tumors
  program_names: [
    'TCGA'
  ]
  sample_types: [
    'Primary Tumor',
    'Primary Blood Derived Cancer - Peripheral Blood',
    'Additional - New Primary'
  ]
  exp_strategy: WGS
  workflow_types: [
    'BWA with Mark Duplicates and BQSR'
  ]
  excl_readgrp_ids: [
    '4872c463-31ec-4b62-8324-bee0ccdc9bdf'
  ]
  data:
    dir: data/gdc

host_filter:
  mode: hisat2

read_classif:
  mode: kraken2

bowtie2:
    build:
      extra: ''
      threads: all
    align:
      extra: ''
      threads: 2

hisat2:
    build:
      extra: ''
      threads: all
    align:
      extra: ''
      threads: 2

biobambam2:
  bamtofastq:
    extra: >-
      exclude=QCFAIL,SECONDARY,SUPPLEMENTARY
      gz=1
      inputformat=bam
      level=5
      tryoq=1

kraken2:
  script_dir: 'external/kraken2/2.1.3-custom/scripts'
  tsearch_unclassif: true
  download:
    use_ftp: false
  k2:
    extra: ''
    threads: 12
    backend: loky
    verbosity: 1
  build:
    extra: ''
    threads: all
  classify:
    extra:
      common: '--use-names --report-minimizer-data --confidence 0.05 --minimum-hit-groups 3'
      paired_end: ''
    threads: 2

krakenuniq:
  download:
    use_rsync: true
    extra: ''
    threads: 2
  build:
    extra: ''
    threads: all
  classify:
    extra:
      common: '--preload-size 100G'
      paired_end: '--check-names'
    threads: all

krakentools:
  script_dir: 'external/krakentools/1.2-custom'
  combine_kreports:
    extra: '--only-combined'

bbmap:
  readlength:
    extra: 'ignorebadquality'
    threads: 2

bracken:
  script_dir: 'external/bracken/3.0-custom'
  build:
    threads: all
  quant:
    levels: [species, genus]
    threshold:
      sg: 0
      rg: 0
